name: rebuild

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: randomgoods/node-image-libs
          registry: docker.io
          tag: latest
          directory: /latest/debian
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: randomgoods/node-image-libs
          registry: docker.io
          tag: slim
          directory: /latest/slim
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: randomgoods/node-image-libs
          registry: docker.io
          tag: lts
          directory: /lts/debian
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: randomgoods/node-image-libs
          registry: docker.io
          tag: lts-slim
          directory: /lts/slim
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
