name: rebuild

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: randomgoods/node-image-libs
          registry: docker.io
          tags:
            - latest
          dockerfile: latest/debian/Dockerfile
          directory: latest/debian
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: randomgoods/node-image-libs
          registry: docker.io
          tags:
            - slim
          dockerfile: latest/slim/Dockerfile
          directory: latest/slim
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: randomgoods/node-image-libs
          registry: docker.io
          tags:
            - lts
          dockerfile: lts/debian/Dockerfile
          directory: lts/debian
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: randomgoods/node-image-libs
          registry: docker.io
          tags:
            - lts-slim
          dockerfile: lts/slim/Dockerfile
          directory: lts/slim
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
